log4j.rootLogger=INFO, CONSOLE

log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
log4j.appender.CONSOLE.target=System.out
log4j.appender.CONSOLE.layout=org.pcsoft.framework.kube.kts.cli.intern.utils.ColorPatternLayout
log4j.appender.CONSOLE.layout.ConversionPattern=[%-5p] %m%n