site_name: Kube KTS User Guide

nav:
  - Home: index.md
  - CLI: cli.md
  - Kotlin Scripts Repository:
      - Chart: kts/chart.md
      - Service: kts/service.md
      - Ingress: kts/ingress.md
      - Values Handling: kts/values.md
